dubbo:
  scan:
    base-packages: com.irdstudio.efp.console.service.impl
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 9090
      server: netty
feign:
  hystrix:
    enabled: true